language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
before_deploy:
- git config --local user.name "HuangXiaojun"
- git config --local user.email "120968816@qq.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
script:
- pyinstaller -F crs_secret_tool.py
deploy:
  provider: releases
  api_key:
    secure: b+be3hkt/eaEKEvmsd9OdDFCOTYLNVN0QyPEff5eJfvLogsnnqjPaVVr5d3FnaihYzjk5PmLpxt8UrRwspPiShP+J12LL3NlpjIGzdGV7Uu9qP9N8kKC5Bpi2yHdsW+1c+CbkMqsgYt3wWud3VP7B0YbIc23cSnBgC/tJayhmDdQU7Os/Neg9YbD6metYpk2FI1qJAi9TuXHDpWWh6JYgVGsBj5zb4cl6q54P3pUR5DoALj33WKQRS0jNxeF5jYYj6vZMLHhW91352lnayyWKMQ6pdyI8lHIFmVOMXlJ4kn3j74XFThWxbfzjPthtWJwnyR5EtPaWLTvo5wcCfbDz1w3JEhO+xQSa+2WWpr5tZ+tk+Uh0neXf3WgZGxdtf/zGOV5Zy9siKsxGBg5yv+Ndpz2jlvnJ4mtbi39fZLoNoxpmJ+DnD1Ed4IUqJfxTkdrUScRgmH+4TPs6vNEXE9SuHVdjIVkH82A+WtrreD8Oh8R79IQU12TQtQ0+6mZiqX13fggEdhuE1uXinOdYjaDrcebmhhc2M1HJMFAGZHCSrscPESxOvC076v9G68YYlmUoOzGwP+t3mKGw2lt2Vh7ptUAmWvNM11FRXtzXI3sHCxy0xgARJcy7G2PxrdxLWzSdNrI91adt/qEHKn7e/EFmK/27OFl3gwL8EzTRd4e0/A=
  file: dist/crs_secret_tool
  skip_cleanup: true
  on:
    repo: ywyt738/crs_secret_tool
